### ISSUE TITLE
Thumbnail plugin - No output

### ISSUE THREAD

**Issue by MarlBurroW** [ebursztein/SiteFab#153]
Output folders are generated but there is no output files.

![img](https://i.imgur.com/aYEDp9G.png)

And as you can see there is something wrong with the path `dev/generated/static/thumbnails/dev/generated/static`

Here is my dev plugin config if it can help:

```yaml
  thumbnails:
    enable: true
    input_dir: dev/generated/static/images/
    output_dir: dev/generated/static/thumbnails/
    thumbnail_sizes:
    - - 120
      - 120
```

Didn't see any errors during the generate
